// getpokemon
export const POKEMON_LIST_RESET = 'POKEMON_LIST_RESET';
export const POKEMON_LIST_PROCESS = 'POKEMON_LIST_PROCESS';
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
export const POKEMON_LIST_FAIL = 'POKEMON_LIST_FAIL';

// getpokemon
export const DETAIL_POKEMON_RESET = 'DETAIL_POKEMON_RESET';
export const DETAIL_POKEMON_PROCESS = 'DETAIL_POKEMON_PROCESS';
export const DETAIL_POKEMON_SUCCESS = 'DETAIL_POKEMON_SUCCESS';
export const DETAIL_POKEMON_FAIL = 'DETAIL_POKEMON_FAIL';

// getpokemon
export const ITEM_LIST_RESET = 'ITEM_LIST_RESET';
export const ITEM_LIST_PROCESS = 'ITEM_LIST_PROCESS';
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS';
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL';
