// getpokemon
export const POKEMON_LIST_RESET = 'POKEMON_LIST_RESET';
export const POKEMON_LIST_PROCESS = 'POKEMON_LIST_PROCESS';
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
export const POKEMON_LIST_FAIL = 'POKEMON_LIST_FAIL';
